name: PHP Linting
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: michaelw90/PHP-Lint@master
